<?php echo $this->doctype() ?>
<html>
<head>
	<?php 
		echo $this->headTitle("Nhac Online - Admin Mangager") ; //set Title website
		echo $this->headLink(array('rel' => 'icon' , 'href' => $this->basePath().'/source/favicon.ico'), 'PREPEND'); 
		echo $this->headLink()->appendStylesheet($this->basePath()."/source/admin/css/ad.css")
							->offsetSetStylesheet("2", $this->basePath()."/source/font-awesome-4.3.0/css/font-awesome.min.css")
							->offsetSetStylesheet("3", $this->basePath()."/source/admin/assets/global/plugins/simple-line-icons/simple-line-icons.css")
							->offsetSetStylesheet("4", $this->basePath()."/source/admin/assets/global/plugins/bootstrap/css/bootstrap.min.css")
							->offsetSetStylesheet("6", $this->basePath()."/source/admin/assets/global/plugins/uniform/css/uniform.default.css")
							->offsetSetStylesheet("7", $this->basePath()."/source/admin/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css")
							->offsetSetStylesheet("8", $this->basePath()."/source/admin/assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css")
							->offsetSetStylesheet("9", $this->basePath()."/source/admin/assets/global/plugins/fullcalendar/fullcalendar.min.css")
							->offsetSetStylesheet("10", $this->basePath()."/source/admin/assets/global/plugins/jqvmap/jqvmap/jqvmap.css")
							->offsetSetStylesheet("11", $this->basePath()."/source/admin/assets/admin/pages/css/tasks.css")
							->offsetSetStylesheet("12", $this->basePath()."/source/admin/assets/global/css/components.css")
							->offsetSetStylesheet("13", $this->basePath()."/source/admin/assets/global/css/plugins.css")
							->offsetSetStylesheet("14", $this->basePath()."/source/admin/assets/admin/layout/css/layout.css")
							->offsetSetStylesheet("15", $this->basePath()."/source/admin/assets/admin/layout/css/themes/default.css")
							->offsetSetStylesheet("16", $this->basePath()."/source/admin/assets/admin/layout/css/custom.css")
							->offsetSetStylesheet("17", $this->basePath()."/source/admin/css/gg_font.css");
		
		echo $this->headScript()->appendFile($this->basePath()."/source/admin/assets/global/plugins/respond.min.js")
							->offsetSetFile("2", $this->basePath()."/source/admin/assets/global/plugins/excanvas.min.js")
							->offsetSetFile("3", $this->basePath()."/source/admin/assets/global/plugins/jquery.min.js")
							->offsetSetFile("4", $this->basePath()."/source/admin/assets/global/plugins/jquery-migrate.min.js")
							->offsetSetFile("5", $this->basePath()."/source/admin/assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js")
							->offsetSetFile("6", $this->basePath()."/source/admin/assets/global/plugins/bootstrap/js/bootstrap.min.js")
							->offsetSetFile("7", $this->basePath()."/source/admin/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js")
							->offsetSetFile("8", $this->basePath()."/source/admin/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js")
							->offsetSetFile("9", $this->basePath()."/source/admin/assets/global/plugins/jquery.blockui.min.js")
							->offsetSetFile("10", $this->basePath()."/source/admin/assets/global/plugins/jquery.cokie.min.js")
							->offsetSetFile("11", $this->basePath()."/source/admin/assets/global/plugins/uniform/jquery.uniform.min.js")
							->offsetSetFile("12", $this->basePath()."/source/admin/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js")
							->offsetSetFile("13", $this->basePath()."/source/admin/assets/global/plugins/jqvmap/jqvmap/jquery.vmap.js")
							->offsetSetFile("14", $this->basePath()."/source/admin/assets/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js")
							->offsetSetFile("15", $this->basePath()."/source/admin/assets/global/plugins/flot/jquery.flot.min.js")
							->offsetSetFile("16", $this->basePath()."/source/admin/assets/global/plugins/flot/jquery.flot.resize.min.js")
							->offsetSetFile("17", $this->basePath()."/source/admin/assets/global/plugins/flot/jquery.flot.categories.min.js")
							->offsetSetFile("18", $this->basePath()."/source/admin/assets/global/plugins/jquery.pulsate.min.js")
							->offsetSetFile("19", $this->basePath()."/source/admin/assets/global/plugins/bootstrap-daterangepicker/moment.min.js")
							->offsetSetFile("20", $this->basePath()."/source/admin/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js")
							->offsetSetFile("21", $this->basePath()."/source/admin/assets/global/plugins/fullcalendar/fullcalendar.min.js")
							->offsetSetFile("22", $this->basePath()."/source/admin/assets/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js")
							->offsetSetFile("23", $this->basePath()."/source/admin/assets/global/plugins/jquery.sparkline.min.js")
							->offsetSetFile("24", $this->basePath()."/source/admin/assets/global/scripts/metronic.js")
							->offsetSetFile("25", $this->basePath()."/source/admin/assets/admin/layout/scripts/layout.js")
							->offsetSetFile("26", $this->basePath()."/source/admin/assets/admin/layout/scripts/quick-sidebar.js")
							->offsetSetFile("27", $this->basePath()."/source/admin/assets/admin/layout/scripts/demo.js")
							->offsetSetFile("28", $this->basePath()."/source/admin/assets/admin/pages/scripts/index.js")
							->offsetSetFile("29", $this->basePath()."/source/admin/assets/admin/pages/scripts/tasks.js");
		echo $this->headMeta()->appendHttpEquiv('Content-Type' , 'text/html; charset=UTF-8' ); // set utf-8 cho website
	?>
</head>
<body class="page-header-fixed page-quick-sidebar-over-content page-style-square"> 
<!-- BEGIN HEADER -->
	<?php require "block/header.php" ?>
<!-- END HEADER -->
<div class="clearfix">
</div>
<!-- BEGIN CONTAINER -->
<div class="page-container">
	<!-- BEGIN SIDEBAR -->
		<?php require "block/menu.php" ?>
	<!-- END SIDEBAR -->
	<!-- BEGIN CONTENT -->
		<?php require "pages/trangchu.php" ?>
	<!-- END CONTENT -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
	<?php require "block/footer.php" ?>
<!-- END FOOTER -->
<script>
jQuery(document).ready(function() {    
   Metronic.init(); // init metronic core componets
   Layout.init(); // init layout
   QuickSidebar.init(); // init quick sidebar
   Demo.init(); // init demo features 
   Index.init();   
   Index.initDashboardDaterange();
   Index.initJQVMAP(); // init index page's custom scripts
   Index.initCalendar(); // init index page's custom scripts
   Index.initCharts(); // init index page's custom scripts
   Index.initChat();
   Index.initMiniCharts();
   Tasks.initDashboardWidget();
});
</script>
<!-- END JAVASCRIPTS -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-37564768-1', 'keenthemes.com');
  ga('send', 'pageview');
</script>
</body>

<!-- END BODY -->
</html>